#!/bin/bash

cd /home/nesl/workspace/newenumnode/Debug
./emumnode &
cd /home/nesl/workspace/enumnode2/Debug
./enumnode2 &
cd /home/nesl/workspace/enumnode3/Debug
./enumnode3 &
cd /home/nesl/workspace/enumnode4/Debug
./emumnode &
cd /home/nesl/workspace/enumnode5/Debug
./emumnode &
cd /home/nesl/workspace/enumnode6/Debug
./emumnode &
cd /home/nesl/workspace/enumnode7/Debug
./emumnode &
cd /home/nesl/workspace/enumnode8/Debug
./emumnode &
cd /home/nesl/workspace/enumnode9/Debug
./emumnode &
cd /home/nesl/workspace/enumnode10/Debug
./emumnode &
cd /home/nesl/workspace/enumnode11/Debug
./emumnode &
cd /home/nesl/workspace/enumnode12/Debug
./emumnode &
cd /home/nesl/workspace/enumnode13/Debug
./emumnode &
cd /home/nesl/workspace/enumnode14/Debug
./emumnode &
cd /home/nesl/workspace/enumnode15/Debug
./emumnode &
cd /home/nesl/workspace/enumnode16/Debug
./emumnode &
cd /home/nesl/workspace/enumnode17/Debug
./emumnode &
cd /home/nesl/workspace/enumnode18/Debug
./emumnode &
cd /home/nesl/workspace/enumnode19/Debug
./emumnode &
cd /home/nesl/workspace/enumnode20/Debug
./emumnode &
cd /home/nesl/workspace/enumnode21/Debug
./emumnode &
cd /home/nesl/workspace/enumnode22/Debug
./emumnode &
cd /home/nesl/workspace/enumnode23/Debug
./emumnode &
cd /home/nesl/workspace/enumnode24/Debug
./emumnode &
cd /home/nesl/workspace/enumnode25/Debug
./emumnode &
cd /home/nesl/workspace/enumnode26/Debug
./emumnode &
cd /home/nesl/workspace/enumnode27/Debug
./emumnode &
cd /home/nesl/workspace/enumnode28/Debug
./emumnode &
cd /home/nesl/workspace/enumnode29/Debug
./emumnode &
cd /home/nesl/workspace/enumnode30/Debug
./emumnode &
