#!/bin/bash

cd /home/nesl/workspace/newenumnode/Debug
./emumnode &
cd /home/nesl/workspace/enumnode2/Debug
./enumnode2 &
cd /home/nesl/workspace/enumnode3/Debug
./enumnode3 &
cd /home/nesl/workspace/enumnode4/Debug
./emumnode &
cd /home/nesl/workspace/enumnode5/Debug
./emumnode &
cd /home/nesl/workspace/enumnode6/Debug
./emumnode &
cd /home/nesl/workspace/enumnode7/Debug
./emumnode &
cd /home/nesl/workspace/enumnode8/Debug
./emumnode &
cd /home/nesl/workspace/enumnode9/Debug
./emumnode &
cd /home/nesl/workspace/enumnode10/Debug
./emumnode &
cd /home/nesl/workspace/enumnode11/Debug
./emumnode &
cd /home/nesl/workspace/enumnode12/Debug
./emumnode &
cd /home/nesl/workspace/enumnode13/Debug
./emumnode &
cd /home/nesl/workspace/enumnode14/Debug
./emumnode &
cd /home/nesl/workspace/enumnode15/Debug
./emumnode &
cd /home/nesl/workspace/enumnode16/Debug
./emumnode &
cd /home/nesl/workspace/enumnode17/Debug
./emumnode &
cd /home/nesl/workspace/enumnode18/Debug
./emumnode &
cd /home/nesl/workspace/enumnode19/Debug
./emumnode &
cd /home/nesl/workspace/enumnode20/Debug
./emumnode &
cd /home/nesl/workspace/enumnode21/Debug
./emumnode &
cd /home/nesl/workspace/enumnode22/Debug
./emumnode &
cd /home/nesl/workspace/enumnode23/Debug
./emumnode &
cd /home/nesl/workspace/enumnode24/Debug
./emumnode &
cd /home/nesl/workspace/enumnode25/Debug
./emumnode &
cd /home/nesl/workspace/enumnode26/Debug
./emumnode &
cd /home/nesl/workspace/enumnode27/Debug
./emumnode &
cd /home/nesl/workspace/enumnode28/Debug
./emumnode &
cd /home/nesl/workspace/enumnode29/Debug
./emumnode &
cd /home/nesl/workspace/enumnode30/Debug
./emumnode &
cd /home/nesl/workspace/enumnode31/Debug
./emumnode &
cd /home/nesl/workspace/enumnode32/Debug
./emumnode &
cd /home/nesl/workspace/enumnode33/Debug
./emumnode &
cd /home/nesl/workspace/enumnode34/Debug
./emumnode &
cd /home/nesl/workspace/enumnode35/Debug
./emumnode &
cd /home/nesl/workspace/enumnode36/Debug
./emumnode &
cd /home/nesl/workspace/enumnode37/Debug
./emumnode &
cd /home/nesl/workspace/enumnode38/Debug
./emumnode &
cd /home/nesl/workspace/enumnode39/Debug
./emumnode &
cd /home/nesl/workspace/enumnode40/Debug
./emumnode &
cd /home/nesl/workspace/enumnode41/Debug
./emumnode &
cd /home/nesl/workspace/enumnode42/Debug
./emumnode &
cd /home/nesl/workspace/enumnode43/Debug
./emumnode &
cd /home/nesl/workspace/enumnode44/Debug
./emumnode &
cd /home/nesl/workspace/enumnode45/Debug
./emumnode &
cd /home/nesl/workspace/enumnode46/Debug
./emumnode &
cd /home/nesl/workspace/enumnode47/Debug
./emumnode &
cd /home/nesl/workspace/enumnode48/Debug
./emumnode &
cd /home/nesl/workspace/enumnode49/Debug
./emumnode &
cd /home/nesl/workspace/enumnode50/Debug
./emumnode &
cd /home/nesl/workspace/enumnode51/Debug
./emumnode &
cd /home/nesl/workspace/enumnode52/Debug
./emumnode &
cd /home/nesl/workspace/enumnode53/Debug
./emumnode &
cd /home/nesl/workspace/enumnode54/Debug
./emumnode &
cd /home/nesl/workspace/enumnode55/Debug
./emumnode &
cd /home/nesl/workspace/enumnode56/Debug
./emumnode &
cd /home/nesl/workspace/enumnode57/Debug
./emumnode &
cd /home/nesl/workspace/enumnode58/Debug
./emumnode &
cd /home/nesl/workspace/enumnode59/Debug
./emumnode &
cd /home/nesl/workspace/enumnode60/Debug
./emumnode &
cd /home/nesl/workspace/enumnode61/Debug
./emumnode &
cd /home/nesl/workspace/enumnode62/Debug
./emumnode &
cd /home/nesl/workspace/enumnode63/Debug
./emumnode &
cd /home/nesl/workspace/enumnode64/Debug
./emumnode &
cd /home/nesl/workspace/enumnode65/Debug
./emumnode &
cd /home/nesl/workspace/enumnode66/Debug
./emumnode &
cd /home/nesl/workspace/enumnode67/Debug
./emumnode &
cd /home/nesl/workspace/enumnode68/Debug
./emumnode &
cd /home/nesl/workspace/enumnode69/Debug
./emumnode &
cd /home/nesl/workspace/enumnode70/Debug
./emumnode &
cd /home/nesl/workspace/enumnode71/Debug
./emumnode &
cd /home/nesl/workspace/enumnode72/Debug
./emumnode &
cd /home/nesl/workspace/enumnode73/Debug
./emumnode &
cd /home/nesl/workspace/enumnode74/Debug
./emumnode &
cd /home/nesl/workspace/enumnode75/Debug
./emumnode &
cd /home/nesl/workspace/enumnode76/Debug
./emumnode &
cd /home/nesl/workspace/enumnode77/Debug
./emumnode &
cd /home/nesl/workspace/enumnode78/Debug
./emumnode &
cd /home/nesl/workspace/enumnode79/Debug
./emumnode &
cd /home/nesl/workspace/enumnode80/Debug
./emumnode &
cd /home/nesl/workspace/enumnode81/Debug
./emumnode &
cd /home/nesl/workspace/enumnode82/Debug
./emumnode &
cd /home/nesl/workspace/enumnode83/Debug
./emumnode &
cd /home/nesl/workspace/enumnode84/Debug
./emumnode &
cd /home/nesl/workspace/enumnode85/Debug
./emumnode &
cd /home/nesl/workspace/enumnode86/Debug
./emumnode &
cd /home/nesl/workspace/enumnode87/Debug
./emumnode &
cd /home/nesl/workspace/enumnode88/Debug
./emumnode &
cd /home/nesl/workspace/enumnode89/Debug
./emumnode &
cd /home/nesl/workspace/enumnode90/Debug
./emumnode &
